# Generated by Django 3.0.4 on 2020-10-12 16:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='p',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
