# Generated by Django 3.0.4 on 2020-10-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_post_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='p',
            new_name='editor',
        ),
    ]
