# Generated by Django 3.0.4 on 2020-10-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
