# Generated by Django 3.0.4 on 2020-11-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_auto_20201122_0527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
    ]
